# Generated by Django 4.2.4 on 2023-08-28 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('draw_history', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DrowHistory',
            new_name='DrawHistory',
        ),
    ]
